# fly.toml file generated for nabilafebriyantiv-final-project-be2969695 on 2022-12-20T13:49:46+07:00

app = "nabilafebriyantiv-final-project-be2969695"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DATABASE_URL = "postgres://postgres:kaoxdk3o9oqrJwb@nabilafebriyantiv-final-project-be2969695-db.internal:5432"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
